### ISSUE TITLE
Can not Clone

### ISSUE THREAD

**Issue by moha2212** [KalyanMurapaka45/Medical-Chatbot-using-Llama-2#1]
i can not clone repo from git clone https://github.com/KalyanMurapaka45/--------------------.git
and i give error when install this repo from url and cant use senteces_transformers

**Comment by KalyanM45** [comment]
I didn't mention the repo, I fixed it
Try this:    git clone https://github.com/KalyanMurapaka45/Medical-Chatbot-using-Llama-2.git
