### ISSUE TITLE
issues on connection to pinecone

### ISSUE THREAD

**Issue by Yazdi9** [KalyanMurapaka45/Medical-Chatbot-using-Llama-2#2]
![Screenshot (808)](https://github.com/KalyanM45/Medical-Chatbot-using-Llama-2/assets/33378412/dd7786d2-d2f9-43fd-8b4b-3b3b5a157816)

**Comment by KalyanM45** [comment]
Follow the README Instructions i.e., create a .env file and place your pinecone API key and try again.
